# Generated by Django 5.0.4 on 2024-09-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reader_model',
            name='palce',
        ),
        migrations.AddField(
            model_name='reader_model',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reader_model',
            name='place',
            field=models.CharField(default=' ', max_length=20),
        ),
    ]
